version: "3"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 4043:443
    depends_on:
      - wordpress
    volumes:
     - wp_vol:/var/www/html
    networks:
      - inception
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - 9000:9000
    volumes:
      - wp_vol:/var/www/html/
    networks:
      - inception
    restart: on-failure
  
  #mariadb:
   # build: ./requirements/mariadb
   # container_name: "mariadb"
    #env_file:
     # - ./.env
    #ports: 
    #  - "127.0.0.1:3306:3306"
    #volumes:
     # - db_vol:/var/lib/mysql
    #networks:
    #  - inception
    #restart: on-failure

networks:
  inception:

volumes:
  wp_vol:
    driver: local
    driver_opts:
      type: none
      device: /mnt/nfs/homes/ldes-cou/Desktop/Inception/Inception/volumes/wp_vol
      o: bind
  
#   db_vol:
#     driver: local
#     driver_opts:
#       type: none
#       device : /home/ldes-cou/data/db_vol
#       o: bind
