version: "3.1"

services:
	nginx:
    	build: ./requirements/nginx
	container_name: nginx
	ports:
	- "443:443"
	#depends_on:	
	#- wordpress
	env_file:
	- ./.env
	networks:
	- inception
	restart: on-failure

 	mariadb:
   	   build: <image_name>:<version>
		container_name: <container_name (no seriously what suprise)>
		ports:
			- <host_port>:<container_port>
		depends_on:
			- <other_service>
		env_file:
			- <path_to_env_file>
		volumes:
			- <volume_name>:<path_in_container>
		restart: <restart_policy>

networks:
	inception:

volumes:
	wp_data:
	 	driver: local
		driver_opts:
			type: none
			device: /home/ldes-cou/data/wp_data
			o: bind
